### PR TITLE
fix #11 (kind of workaround)

### LINKED ISSUE #11: @Transactional and TransactionalAction conception problem - does not work with Secure Social plugin
Hi,

I've found a critical bug in the play java ebean plugin.
In my opinion, there is a confusion in the usage of promise and action wrappers (`@With` ...).

Look at this portion of code from the class play.db.ebean.TransactionalAction: (https://github.com/playframework/play-ebean/blob/268c771426398353af39c0c45fb458122cc57a6b/play-ebean/src/main/java/play/db/ebean/TransactionalAction.java)

```
/**
 * Wraps an action in an Ebean transaction.
 */
public class TransactionalAction extends Action<Transactional> {

    public F.Promise<Result> call(final Context ctx) throws Throwable {
        return Ebean.execute(new TxCallable<F.Promise<Result>>() {
            public F.Promise<Result> call() {
                try {
                    return delegate.call(ctx);
                } catch (RuntimeException e) {
                    throw e;
                } catch (Throwable t) {
                    throw new RuntimeException(t);
                }
            }
        });
    }

}
```

The EBean transaction starts before entering the `public F.Promise<Result> call()` method, and is commited or rollbacked depending if there is an exception thrown at the end of `call()`.

In this callable, the result of `delegate.call(ctx)` is returned. This result is of kind `F.Promise<Result>`.
A promise is a "promise of response", but nothing tell us that the underlying action has already been executed **after** the delegate call. Moreover, nothing tell us that it will be executed in **the same thread**.

In the common case where no play plugins are used, this portion of code works: but I insist on the point that this case is a special case, because I don't know why but when the F.Promise<Result> is returned, the underlying action has already been executed in the current thread. I think that this is a misconception but that's my opinion.
Moreover nothing forbid in the current API to execute the delegate action in another thread and later (I mean **after** the transaction commit).

For example, if you use the popular and almost vital plugin **Secure Social**, this code does not work anymore. There is no exception thrown, but the subsequent action is executed outside the transaction, and this is a very **bad** idea.

Indeed, in this case, the delegate returns a F.Promise<Result> where the action has not yet been executed. And again, I insist on the point that this is not a Secure Social bug in my opinion because the promise API is made to allow that!

For information, I'm using Secure Social 3.0-M3 and Play Framework 2.3.8.

Currently, I'm trying to understand how to really "wrap" the action execution using the F.Promise API, but any help would be really appreciated.

### PR DESCRIPTION
**Pull request by rlamarche**
Fix proposal for #11.
The solution is not perfect but it's all I have.

The solution is to put the transactional action wrapper just before the real request.
In this case, the action is executed in the same thread as the action wrapper and it works fine when SecureSocial is used.

Of course, the concept is still bad in my opinion because we always return a promise instead of a Result.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @Romlam,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by typesafehub-validator** [comment]
Hi @rlamarche,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by benmccann** [comment]
Looks like the CLA is signed: http://www.typesafe.com/contribute/cla/check/rlamarche

**Comment by benmccann** [comment]
@rlamarche this would need to be rebased

**Pull request closed without merging**
