### PR TITLE
Upgrade Ebean to prior version 9.1.2

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
This pull request upgrade Ebean version to prior version 9.1.2 released since few days. This new Ebean version fix major issues :

- Can use Play with H2 Database and Ebean version 9.x
- Query cache collision
- Clash on bind hash value for query cache with consecutive values
- @AttributeOverride (not wrapped in @AttributeOverrides) is not applied
- DBMigration Generates wrong ddl for UUID type

More information about Ebean 9.1.2 at https://github.com/ebean-orm/ebean/releases

### CODE REVIEW

**Comment by 0xbaadf00d** [comment]
@ZeerDonker could you try this version ?

**Comment by 0xbaadf00d** [comment]
@ZeerDonker here a working version with Ebean 9.1.1

**Comment by 0xbaadf00d** [comment]
(ping) Any chance to have this PR merged ?

**Comment by marcospereira** [comment]
Sorry for taking so long to give you some feedback.

Do you mind to update this PR with Ebean 9.2.1 and Ebean-agent 8.2.1?

Thanks.

**Comment by 0xbaadf00d** [comment]
@marcospereira I update PR today

**Comment by 0xbaadf00d** [comment]
New PR at #106

**Pull request closed without merging**
