### PR TITLE
Upgrade for Ebean 6.7.1

### PR DESCRIPTION
**Pull request by Ronnie76er**
Upgrade for Ebean 6.7.1.  This resolves issue #53

### CODE REVIEW

**Comment by Ronnie76er** [comment]
Changed this to an upgrade for 6.8.1, just released: https://github.com/ebean-orm/avaje-ebeanorm/releases/tag/avaje-ebeanorm-6.8.1

**Comment by corrspt** [comment]
Hey @Ronnie76er, sorry for intruding on this PR, but I've been trying to use the latest EBean with Play (2.4.2) and I've been having lots of issues (ranging from the EBean not being able to find my Entities, to more weird issues). Looking by the PR, I assume you can use the latest version of EBean in a Play Project correct?

I'm a beginner with Play/Sbt/Plugins.

I thought that I would be able to use the play-ebean plugin if I cloned the repo and added your changes then publish the plugin to a local repository and then using it inside my play-app, but so far I've stuck on not being able to make the Play application find the plugin in the local repository (I've used activator +publishLocal) it appears that the plugin is placed in a directory that Play is not expecting - I added this to plugins.sbt - addSbtPlugin("com.typesafe.play" % "play-ebean" % "1.0.1-SNAPSHOT") ) I've tried moving the generated plugin to the correct folder, but now I get these errors:

```
com.typesafe.play#play-ebean;1.0.1-SNAPSHOT: java.text.ParseException: inconsistent module descriptor file found in '/Users/useruser/.ivy2/local/com.typesafe.play/play-ebean/scala_2.10/sbt_0.13/1.0.1-SNAPSHOT/ivys/ivy.xml': 
bad scalaVersion found in /Users/useruser/.ivy2/local/com.typesafe.play/play-ebean/scala_2.10/sbt_0.13/1.0.1-SNAPSHOT/ivys/ivy.xml: expected='2.10' found='null';
bad sbtVersion found in /Users/useruser/.ivy2/local/com.typesafe.play/play-ebean/scala_2.10/sbt_0.13/1.0.1-SNAPSHOT/ivys/ivy.xml: expected='0.13' found='null';
```

I have no idea where to put the values for scalaVersion or sbtVersion (and I've tried several places in the ivy.xml file). I've also had to change the pom.xml file that's generated by publishLocal.

Thanks in advance for any help

**Comment by Ronnie76er** [comment]
You must also `plugin/publishLocal` to deploy the plugin as well.

**Comment by corrspt** [comment]
Thanks a bunch @Ronnie76er, with that Tip I could finally make it work. A million thanks :+1:  Hoping that @jroper or @marcospereira can merge this into the repo so that everyone can benefit from this.

**Comment by jroper** [comment]
play-ebean 2.0.0 has been released with this upgrade.

**Comment by Ronnie76er** [comment]
Thanks @jroper!

**Pull request merged**
