### PR TITLE
New versioning branch for play framework 2.5 and Ebean 10.3.2

### PR DESCRIPTION
**Pull request by wobu**
branch supporting play framework 2.5.X and Ebean 10.3.2

this pull request shall support a new plugin release, asked in issue https://github.com/playframework/play-ebean/issues/121

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @wobu,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by wobu** [comment]
signed the CLA

**Comment by marcospereira** [comment]
Hi @wobu, first of all, sorry for the long time without a proper answer.

I think the best approach here is to have another branch (maybe 3.2.x?) since these changes are not compatible with 3.1.x and I want to avoid releasing `3.1.1` with breaking changes.

What do you think? If you agree, I can just create another branch and you can then target it.

**Comment by wobu** [comment]
that would be great :)

**Pull request merged**
