### PR TITLE
Added version 4.0.6 to README

### PR DESCRIPTION
**Pull request by PromanSEW**

### CODE REVIEW

**Comment by PromanSEW** [comment]
@marcospereira please review

**Comment by marcospereira** [comment]
> I think it will be 4.0.6 without 4.0.4-4.0.5 releases. WDYT?

Exactly, there is no problem using 4.0.4 and 4.0.5, they are valid versions (and virtually identical), but without sbt 1.0 support.

Thanks for this PR, @PromanSEW.

**Comment by PromanSEW** [comment]
@marcospereira what versions are should be added to README?

**Comment by PromanSEW** [comment]
I think `4.0.6` is enough

**Comment by PromanSEW** [comment]
I leave only actual versions for each Play and Ebean updates

**Comment by PromanSEW** [comment]
@marcospereira please merge or review changes

**Pull request merged**
