### PR TITLE
Remove deprecated method

### LINKED ISSUE #278: NoClassDefFoundError: io/ebean/EbeanServer
I updated Ebean to 13.6.0, and got this exception:
```
play.api.UnexpectedException: Unexpected exception[NoClassDefFoundError: io/ebean/EbeanServer]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:258)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:148)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:302)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:224)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1307)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
Caused by: java.lang.NoClassDefFoundError: io/ebean/EbeanServer
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48)
	at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:811)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:730)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:430)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:177)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:670)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:627)
Caused by: java.lang.ClassNotFoundException: io.ebean.EbeanServer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48)
	at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:811)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:730)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:430)
```
Links:
https://github.com/ebean-orm/ebean/releases/tag/ebean-parent-13.6.0
https://github.com/ebean-orm/ebean/pull/2662

### PR DESCRIPTION
**Pull request by PromanSEW**
Really fixes #278 
See discussion here:
https://github.com/playframework/play-ebean/issues/278#issuecomment-1123982804
Removing this method is really necessary for binary compatibility with Ebean 13.6.0 and newer

### CODE REVIEW

**Comment by PromanSEW** [comment]
I don't know what is wrong with scalafmt
```
sbt:play-ebean-root> validateCode 
[success] Total time: 0 s, completed 12 ╨╝╨░╤П 2022 ╨│., 0:33:06
[info] scalafmt: Checking 2 Scala sources (D:\Documents\GitHub\play-ebean)...
[warn] scalafmt: D:\Documents\GitHub\play-ebean\project\Common.scala isn't formatted properly!
[warn] scalafmt: D:\Documents\GitHub\play-ebean\project\Dependencies.scala isn't formatted properly!
[error] scalafmt: 2 files must be formatted (D:\Documents\GitHub\play-ebean)
[error] (Compile / scalafmtSbtCheck) scalafmt: 2 files must be formatted (D:\Documents\GitHub\play-ebean)
[error] Total time: 1 s, completed 12 ╨╝╨░╤П 2022 ╨│., 0:33:07
sbt:play-ebean-root> scalafmtAll
[success] Total time: 0 s, completed 12 ╨╝╨░╤П 2022 ╨│., 0:33:18
```

**Comment by mkurz** [comment]
@PromanSEW The problem was `...scalafmtSbtCheck...`, to resolve this you have to run `scalafmtSbt`. I pushed the fix.

**Review by mkurz — APPROVED** [review]

**Comment by mkurz** [comment]
Thanks!

**Comment by mkurz** [comment]
New release: https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC6

**Pull request merged**
