### PR TITLE
Upgrade Ebean

### PR DESCRIPTION
**Pull request by konradr25**
- Ebean ORM from 8.4.1 to 10.1.5
- Ebean agent from 8.1.1 to 10.1.2

More details about improvements:
https://github.com/ebean-orm/ebean/releases

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @konradr25,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by marcospereira** [comment]
Hey @konradr25,

The upgrade broke the build:

https://travis-ci.org/playframework/play-ebean/jobs/195929065#L1203

You can reproduce it locally by running `sbt clean test`.

**Comment by marcospereira** [comment]
Also, please consider other possible compatibility changes there were discussed at #106.

**Comment by benmccann** [comment]
I've submitted another PR for this: https://github.com/playframework/play-ebean/pull/109

**Pull request closed without merging**
