### PR TITLE
upgrade ebeanorm to 6.3.1 and ebeanorm-agent to 4.5.4

### PR DESCRIPTION
**Pull request by be1ive**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @be1ive,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by marcospereira** [comment]
Thanks @be1ive,

@jroper as discussed in #49 and #50, maybe we should release a new version of play-ebean and then we can upgrade both Ebean version and also start to build against play's master branch.

WDYT?

**Comment by jroper** [comment]
Yeah.  One question is what should the version numbers be.  If ebean has bumped its major number, perhaps the upgrade to 6 should bump play-ebeans major number?  I think we should create a play-2.4.x branch, where we can continue to cut new play-ebean releases from, and we can cut 3.0.0 from there with this upgrade.  How does that sound?

**Comment by opensrcken** [comment]
This is a very useful PR that allows one to leverage Json columns in Postgres with minimal hassle with the addition of the `DbJson` annotation.

However, I am trying to run this version of the ebean plugin and am getting lots of the following when the play server is hot-reloaded. Perhaps I have upgraded the plugin incorrect, or maybe there's something else that needs to be fixed.

Exception in thread "pool-8-thread-5" javax.persistence.PersistenceException: java.sql.SQLException: Pool has been shutdown
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:295)
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:1986)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:169)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1193)
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1052)
	at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1039)
	at com.avaje.ebean.Model$Find.byId(Model.java:519)
	at models.Notification.saveWithOriginator(Notification.java:50)
	at daos.NotificationDao.persistNotification(NotificationDao.java:41)
	at daos.NotificationDao.persistNotification(NotificationDao.java:17)
	at libs.notifications.NotificationControlCenter.onNotificationInput(NotificationControlCenter.java:30)
	at utils.InitializeRabbitMqListeners$NewNotificationListener$NotificationPersister.run(InitializeRabbitMqListeners.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Pool has been shutdown
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:89)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:138)
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:277)
	... 14 more

**Comment by marcospereira** [comment]
@jroper that sounds good to me. :-)

**Comment by ZeerDonker** [comment]
Hey, this is probably a stupid question. 

But how would I use a modified plugin like the above change set, instead of the plugin that is currently released? 

(The released way is adding [addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "1.0.0")] in project/plugins.sbt and adding the PlayEbean on the [lazy val root = (project in file(".")).enablePlugins(PlayJava , PlayEbean) ] line in the build.sbt file. )

([activator publish-local] , publishes the jar & etc. files locally, but a line like [addSbtPlugin("com.typesafe.play" % "play-ebean" % "1.0.1-SNAPSHOT") ] in the project/plugins.sbt file won't work, and while a line like ["com.typesafe.play" %% "play-ebean" % "1.0.1-SNAPSHOT",] in the build.sbt will work in finding the jar file, it will cause errors like 'Unable to create injector' & will want the PlayEbean item removed from the enablePlugins method. )

**Comment by jroper** [comment]
@ZeerDonker due to the way cross building works in sbt (it applies the same scala versions to all sub projects), and because sbt plugins must not be cross built because sbt itself is not cross built, the root project doesn't aggregate the plugin project in play-ebean. so, if you want to build it locally, you should do `sbt +publishLocal plugin/publishLocal`.  This will cross build and publish the play ebean library, as well as publish the play ebean sbt plugin.

**Comment by ZeerDonker** [comment]
@jroper  Thanks :)

**Comment by opensrcken** [comment]
I'm getting the following error when trying to use this locally, and I'm a relative SBT newb, so I'm having trouble making heads or tails of this:

[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/ken47/dev/lolphd/play-server/}root:
[error]    com.typesafe.akka:akka-actor _2.10, _2.11
[error]    com.typesafe.play:twirl-api _2.11, _2.10
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:update) Conflicting cross-version suffixes in: com.typesafe.akka:akka-actor, com.typesafe.play:twirl-api
java.lang.RuntimeException: Conflicting cross-version suffixes in: com.typesafe.akka:akka-actor, com.typesafe.play:twirl-api
	at scala.sys.package$.error(package.scala:27)
	at sbt.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:46)
	at sbt.ConflictWarning$.apply(ConflictWarning.scala:32)
	at sbt.Classpaths$$anonfun$66.apply(Defaults.scala:1164)
	at sbt.Classpaths$$anonfun$66.apply(Defaults.scala:1161)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Conflicting cross-version suffixes in: com.typesafe.akka:akka-actor, com.typesafe.play:twirl-api
[error] Use 'last' for the full log.

Within the activator shell for the play project:

[play-server] $ what-depends-on com.typesafe.play twirl-api_2.10 1.1.1
[info] Updating {file:/Users/ken47/dev/lolphd/play-server/}root...
[info] Resolving com.typesafe.akka#akka-testkit_2.11;2.3.8 ...
[info] Done updating.
[info] com.typesafe.play:twirl-api_2.10:1.1.1 [S]
[info]   +-com.typesafe.play:routes-compiler_2.10:2.4.3 [S]
[info]   | +-com.typesafe.play:sbt-plugin:2.4.3
[info]   |   +-com.typesafe.play:play-ebean_2.11:1.0.1-SNAPSHOT
[info]   |     +-play-server:play-server_2.11:1.0-SNAPSHOT [S]
[info]   |
[info]   +-com.typesafe.play:twirl-compiler_2.10:1.1.1 [S]
[info]     +-com.typesafe.sbt:sbt-twirl:1.1.1
[info]       +-com.typesafe.play:sbt-plugin:2.4.3
[info]         +-com.typesafe.play:play-ebean_2.11:1.0.1-SNAPSHOT
[info]           +-play-server:play-server_2.11:1.0-SNAPSHOT [S]
[info]

Any insight?

**Comment by jroper** [comment]
Closing in favour of #53.

**Pull request closed without merging**
