### PR TITLE
Fixes publish release to Sonatype repository.

### LINKED ISSUE #216: Bintray Download for 6.1.0 down
As we had some problems very similar to #214 we updated play-ebean to 6.1.0-RC3 with the following line in `plugins.sbt`:
`addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.1.0-RC3")`

This worked fine but today I experimented with building in a docker container and then got the exception that play-ebean couldn't be loaded as `https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.13/6.1.0-RC3/play-ebean_2.13-6.1.0-RC3.pom` returned a 403. And in fact, the complete artifact directory at https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.13/6.1.0-RC3 returns a 403. 

I'm not enough into maven, bintray etc. so this is purely a speculation but could this be related to the [bintray sunset](https://www.jfrog.com/confluence/display/BT/Welcome+to+JFrog+Bintray)? According to this link the community central was shut down on May 1st. But maybe this ist just temporary, I don't know.

It looks like the 6.0.0 is hosted directly on maven central so it isn't affected. But as the ebean version changed I fear that downgrading would produce a lot of errors in my project, so is there a way to set a mirror for downloading play-ebean? Or could a contributor move the artifacts away from bintray?

### PR DESCRIPTION
**Pull request by felipebonezi**
Fixes #216, #221 reference to PR #217
It will help to evolve #208 and get things on track!

### CODE REVIEW

**Review by lapidus79 — APPROVED** [review]

**Comment by felipebonezi** [comment]
@lapidus79 hey, tks for merge.
Could you create a new pre-release and write how to use the RC image available?

It will help our Play Ebean community to Test and use on their projects. 😁

**Comment by lapidus79** [comment]
Will do it in a couple of hours

**Comment by lapidus79** [comment]
@felipebonezi seems that the publish failed for some reason. Any ideas? 

https://app.travis-ci.com/github/playframework/play-ebean/jobs/540058280

**Comment by felipebonezi** [comment]
> @felipebonezi seems that the publish failed for some reason. Any ideas? 
> 
> https://app.travis-ci.com/github/playframework/play-ebean/jobs/540058280

I think it must be in both settings on build.sbt (play-ebean and sbt-play-ebean)

Let me add.

**Comment by lapidus79** [comment]
@felipebonezi or could it be that it for some reason is trying to publish the play-ebean-root project

```
2021-09-28 15:43:18.111Z  info [SonatypeService] No previous staging repository for [sbt-sonatype] play-ebean-root 6.2.0-RC1 was found  - (SonatypeService.scala:96)
2021-09-28 15:43:22.218Z error [Sonatype] [MISSING_PROFILE] Profile com.typesafe.play is not found. Check your sonatypeProfileName setting in build.sbt  - (Sonatype.scala:425)
```

even though the root project has "publish / skip := true" in build.sbt 🤔 

````
lazy val root = project
  .in(file("."))
  .aggregate(core, plugin)
  .disablePlugins(MimaPlugin)
  .settings(
    name := "play-ebean-root",
    crossScalaVersions := Nil,
    publish / skip := true
  )
```

**Pull request merged**
