### PR TITLE
Upgrade to Play 2.5.0-RC1

### PR DESCRIPTION
**Pull request by jroper**

### CODE REVIEW

**Comment by marcospereira** [comment]
Build failed with:

```
[info] [error] /tmp/sbt_82d249de/enhancement/tests/models/TestTask.java:11:  play.Application cannot be converted to play.test.FakeApplication
[info] [error] fakeApplication(inMemoryDatabase())
[info] [info] /tmp/sbt_82d249de/enhancement/tests/models/TestTask.java: /tmp/sbt_82d249de/enhancement/tests/models/TestTask.java uses or overrides a deprecated API.
[info] [info] /tmp/sbt_82d249de/enhancement/tests/models/TestTask.java: Recompile with -Xlint:deprecation for details.
[info] [error] (test:compileIncremental) javac returned nonzero exit code
[info] [error] Total time: 9 s, completed Feb 17, 2016 5:37:16 AM
[error] x sbt-ebean / enhancement
[error]    {line 1}  Command failed: test failed
```

**Comment by marcospereira** [comment]
Close/reopen because travis build was hanging up in some way.

**Comment by mkurz** [comment]
@marcospereira You don't need to close/reopen pull requests to trigger a CI run. Just  log in to travis, go to the failed build and the hit refresh button (small round button with round arrow inside) on the very right side. See here: https://travis-ci.org/playframework/play-ebean/builds/91802550 When you hover over the button it says "Restart Build"

**Comment by marcospereira** [comment]
@mkurz did that, but travis was having some bad time. ;-)

**Comment by mkurz** [comment]
OK :+1: :smile:

**Pull request merged**
